### ISSUE TITLE
concurrency hashmap write issue

### ISSUE THREAD

**Issue by u007** [markbates/pop#136]
on development, sometimes im encountering this:
happened on both go 1.8 and 1.9

```
fatal error: concurrent map writes

goroutine 57 [running]:
runtime.throw(0x4bef057, 0x15)
/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:605 +0x95 fp=0xc420907ab0 sp=0xc420907a90 pc=0x402cd05
runtime.mapassign_faststr(0x4ae1ea0, 0xc4201fff20, 0xc420312b48, 0x8, 0x0)
/usr/local/Cellar/go/1.9/libexec/src/runtime/hashmap_fast.go:607 +0x4f5 fp=0xc420907b30 sp=0xc420907ab0 pc=0x400f885
github.com/markbates/pop.(*sqlBuilder).buildColumns(0xc420705680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
$GOPATH/src/github.com/markbates/pop/sql_builder.go:190 +0x1f2 fp=0xc420907d00 sp=0xc420907b30 pc=0x454bd12
github.com/markbates/pop.(*sqlBuilder).buildSelectSQL(0xc420705680, 0x0, 0x0)
$GOPATH/src/github.com/markbates/pop/sql_builder.go:66 +0x40 fp=0xc420907de0 sp=0xc420907d00 pc=0x4549d40
github.com/markbates/pop.(*sqlBuilder).compile(0xc420705680)
$GOPATH/src/github.com/markbates/pop/sql_builder.go:52 +0x2a4 fp=0xc420907e80 sp=0xc420907de0 pc=0x4549ca4
github.com/markbates/pop.(*sqlBuilder).String(0xc420705680, 0x1, 0xc4207d87e0)
$GOPATH/src/github.com/markbates/pop/sql_builder.go:31 +0x59 fp=0xc420907e98 sp=0xc420907e80 pc=0x4549919
github.com/markbates/pop.Query.ToSQL(0xc4207d87b0, 0x1, 0xc4207d87e0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
$GOPATH/src/github.com/markbates/pop/query.go:105 +0xbc fp=0xc420907fb0 sp=0xc420907e98 pc=0x4547c1c
github.com/markbates/pop.genericSelectOne(0x51bbf80, 0xc42023e148, 0xc4207d8810, 0xc4207d87b0, 0x1, 0xc4207d87e0, 0x1, 0x1, 0x0, 0x0, ...)
$GOPATH/src/github.com/markbates/pop/dialect.go:107 +0x97 fp=0xc4209080f8 sp=0xc420907fb0 pc=0x453ae37
github.com/markbates/pop.(*postgresql).SelectOne(0xc42024c140, 0x51bbf80, 0xc42023e148, 0xc4207d8810, 0xc4207d87b0, 0x1, 0xc4207d87e0, 0x1, 0x1, 0x0, ...)
$GOPATH/src/github.com/markbates/pop/postgresql.go:68 +0x87 fp=0xc4209081f8 sp=0xc4209080f8 pc=0x4545537
github.com/markbates/pop.(*Query).First.func1(0xbe6ef553401502e8, 0x3980d482a5)
$GOPATH/src/github.com/markbates/pop/finders.go:51 +0xf9 fp=0xc420908320 sp=0xc4209081f8 pc=0x454fce9
github.com/markbates/pop.(*Connection).timeFunc(0xc42023c200, 0x4bdacec, 0x5, 0xc4209083c0, 0xc42085aae0, 0x2)
$GOPATH/src/github.com/markbates/pop/connection.go:175 +0x53 fp=0xc420908390 sp=0xc420908320 pc=0x4538bd3
github.com/markbates/pop.(*Query).First(0xc4202475f0, 0x4b68f40, 0xc420245180, 0xc42085aae0, 0x2)
$GOPATH/src/github.com/markbates/pop/finders.go:48 +0x83 fp=0xc4209083f0 sp=0xc420908390 pc=0x453d593
project/middleware.glob..func1.1.1(0x51be040, 0xc4202a4380, 0x0, 0x0)
$GOPATH/src/project/middleware/auth.go:154 +0x19674 fp=0xc4209175b0 sp=0xc4209083f0 pc=0x475a9d4
project/middleware.DefaultTemplate.func1(0x51be040, 0xc4202a4380, 0x6, 0x4b127a0)
$GOPATH/src/project/middleware/template.go:14 +0x8b fp=0xc4209175f0 sp=0xc4209175b0 pc=0x4740ceb
project/middleware.ParamBinderMiddleware.func1(0x51be040, 0xc4202a4380, 0x4bdb33b, 0x5)
$GOPATH/src/project/middleware/param_binder.go:149 +0xae fp=0xc420917638 sp=0xc4209175f0 pc=0x4740bfe
project/middleware.LanguageMiddleware.func1(0x51be040, 0xc4202a4380, 0x2, 0x4bbc2a0)
$GOPATH/src/project/middleware/language.go:53 +0x49b fp=0xc4209176f8 sp=0xc420917638 pc=0x474085b
github.com/gobuffalo/buffalo/middleware.glob..func1.1.1.1(0xc4203c4d40, 0x0, 0x0)
$GOPATH/src/github.com/gobuffalo/buffalo/middleware/pop_transaction.go:28 +0xea fp=0xc420917750 sp=0xc4209176f8 pc=0x48ad6fa
github.com/markbates/pop.(*Connection).Transaction.func1(0x38873c01, 0xc420411ea0)
$GOPATH/src/github.com/markbates/pop/connection.go:109 +0x62 fp=0xc4209177b0 sp=0xc420917750 pc=0x454e742
github.com/markbates/pop.(*postgresql).Lock(0xc42024c140, 0xc420411ea0, 0x20, 0x4b2bca0)
$GOPATH/src/github.com/markbates/pop/postgresql.go:156 +0x27 fp=0xc4209177d0 sp=0xc4209177b0 pc=0x4546ad7
github.com/markbates/pop.(*Connection).Transaction(0xc42023c200, 0xc420411e80, 0x4576553, 0x4ae2500)
$GOPATH/src/github.com/markbates/pop/connection.go:103 +0x7d fp=0xc420917810 sp=0xc4209177d0 pc=0x45385ad
github.com/gobuffalo/buffalo/middleware.glob..func1.1.1(0x51be040, 0xc4202a4380, 0x7, 0x4a9b880)
$GOPATH/src/github.com/gobuffalo/buffalo/middleware/pop_transaction.go:20 +0x92 fp=0xc420917860 sp=0xc420917810 pc=0x48ad7d2
project/middleware.FormatMiddleware.func1(0x51be040, 0xc4202a4380, 0xc420336500, 0x51be040)
$GOPATH/src/project/middleware/format.go:42 +0x4e6 fp=0xc420917940 sp=0xc420917860 pc=0x473fff6
...
```

**Comment by markbates** [comment]
Can you provide a project or instructions on how to reproduce this?

**Comment by stanislas-m** [comment]
@markbates, I think this is due to a race condition in the sql_builder: the columnCache is not protected by a mutex.

**Comment by markbates** [comment]
@stanislas-m want to take a crack at fixing it?

**Comment by stanislas-m** [comment]
@markbates Sure!
